kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model20b
  labels:
    app: granite-20-lcpp-py
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
  storageClassName: gp2
  volumeMode: Filesystem

