kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models
  namespace: 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
  storageClassName: gp2
  volumeMode: Filesystem
